"""Generate the Containerfile for a development environment image."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field

from . import lcov
from .catalog import CATALOG_BY_KEY, Distro
from .extras import (
    Extra,
    ExtraKind,
    extra_packages,
    needs_rust,
    resolve,
)

#: Where rustup and cargo live in the image. Outside any user home, so the
#: toolchain works for whichever user the container runs as.
RUSTUP_HOME = "/usr/local/rustup"
CARGO_HOME = "/usr/local/cargo"


def distro_rust_packages(distro_key: str) -> tuple[str, ...]:
    """The distro's own Rust package names, which rustup replaces."""
    spec = CATALOG_BY_KEY.get("rust")
    names = set(spec.names_for(distro_key)) if spec is not None else set()
    # cargo is a separate package on the apt distros, and rust-all is Debian's
    # umbrella; neither appears in the comparison catalogue.
    names.update({"cargo", "rust-all"})
    return tuple(sorted(names))


@dataclass(slots=True)
class ImageSpec:
    distro: Distro
    packages: list[str] = field(default_factory=list)
    selected_extras: set[str] = field(default_factory=set)
    #: A rustup toolchain spec: "stable", or a pinned version like "1.98.0".
    rust_toolchain: str = "stable"
    image_name: str = "devenv"
    image_tag: str = "latest"
    workdir: str = "/work"
    #: Resolved release tags for SDK extras, keyed by extra key. Populated by
    #: the caller so generation itself stays free of network access.
    sdk_versions: dict[str, str] = field(default_factory=dict)

    def version_for(self, extra: Extra) -> str:
        return self.sdk_versions.get(extra.key) or extra.fallback_tag

    @property
    def reference(self) -> str:
        return f"{self.image_name}:{self.image_tag}"

    @property
    def extras(self) -> list[Extra]:
        return resolve(self.selected_extras)

    @property
    def sdk_extras(self) -> list[Extra]:
        return [e for e in self.extras if e.kind is ExtraKind.SDK]

    @property
    def needs_rust(self) -> bool:
        """Only the rustup and cargo extras need a toolchain; an SDK does not."""
        return needs_rust(self.selected_extras)


def generate(spec: ImageSpec) -> str:
    """Render the Containerfile."""
    distro = spec.distro
    lines: list[str] = [
        "# Generated by DevEnv Forge.",
        f"# Base: {distro.label}",
        "#",
        "# Pin the base image by digest before distributing this to a team;",
        "# a tag moves and two people would not get the same image.",
        f"FROM {distro.base_image}",
        "",
    ]

    packages = list(spec.packages)
    dropped: list[str] = []
    if spec.needs_rust:
        # rustup brings its own rustc and cargo. Installing the distro's Rust
        # as well leaves two toolchains fighting over PATH, and the distro one
        # cannot satisfy "rustup target add" anyway.
        for name in distro_rust_packages(distro.key):
            if name in packages:
                packages.remove(name)
                dropped.append(name)

    # Extras carry their own build dependencies whether or not Rust is involved.
    extra_names = list(extra_packages(spec.selected_extras, distro.key))
    if spec.needs_rust or spec.sdk_extras:
        # Both the rustup installer and a git clone fetch over TLS.
        extra_names = [*distro.tls_packages, *extra_names]
    for name in extra_names:
        if name not in packages:
            packages.append(name)

    if dropped:
        lines += [
            f"# {', '.join(dropped)} omitted: rustup supplies the Rust toolchain",
            "# below, and two toolchains on PATH is a trap.",
            "",
        ]

    if packages:
        lines += [
            "# Distribution packages",
            f"RUN {distro.install_run(packages)}",
            "",
        ]

    if spec.needs_rust:
        lines += _rust_section(spec)

    if spec.sdk_extras:
        lines += _sdk_section(spec)

    # After the slow layers, so changing it never rebuilds Rust or the SDKs.
    if lcov.installs_lcov(packages, distro.key):
        lines += lcov.section()

    lines += [
        f"WORKDIR {spec.workdir}",
        "",
        "# A smoke test, so a broken toolchain fails the build rather than the",
        "# first person to use the image.",
        f"RUN {_verify_command(spec)}",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _rust_section(spec: ImageSpec) -> list[str]:
    """rustup bootstrap plus the selected extras.

    A distro's rustc package does not provide rustup, so rustup is installed
    from upstream. That also keeps the Rust version independent of whatever the
    distro happens to ship.
    """
    lines = [
        "# Rust toolchain. Installed through rustup rather than the distro",
        "# package, because rustup is what 'rustup target add' needs and the",
        "# distro rustc does not provide it.",
        f"ENV RUSTUP_HOME={RUSTUP_HOME} \\",
        f"    CARGO_HOME={CARGO_HOME} \\",
        f"    PATH={CARGO_HOME}/bin:$PATH",
        f"ARG RUST_TOOLCHAIN={spec.rust_toolchain}",
        "# Downloaded to a file rather than piped into sh. A pipe hides a failed",
        "# download behind the shell's exit status, and the usual guard against",
        "# that, SHELL with -o pipefail, is ignored under the OCI image format",
        "# and unsupported by the busybox shell Alpine uses.",
        "RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \\",
        "        -o /tmp/rustup-init.sh \\",
        ' && sh /tmp/rustup-init.sh -y --no-modify-path --profile minimal \\',
        '        --default-toolchain "$RUST_TOOLCHAIN" \\',
        " && rm /tmp/rustup-init.sh \\",
        f" && chmod -R a+w {RUSTUP_HOME} {CARGO_HOME}",
        "",
    ]

    targets = [e for e in spec.extras if e.kind is ExtraKind.RUSTUP_TARGET]
    components = [e for e in spec.extras if e.kind is ExtraKind.RUSTUP_COMPONENT]
    installs = [e for e in spec.extras if e.kind is ExtraKind.CARGO_INSTALL]

    if targets or components:
        lines.append("# Extras: cross-compilation targets and toolchain components")
        for extra in (*targets, *components):
            lines.append(f"RUN {extra.run_line}")
        lines.append("")

    if installs:
        lines.append("# Extras: cargo-installed tools. These compile from source.")
        for extra in installs:
            # One layer each: probe-rs-tools takes minutes, and a separate
            # layer means editing the others does not rebuild it.
            lines.append(f"RUN {extra.run_line}")
        lines.append(f"RUN rm -rf {CARGO_HOME}/registry {CARGO_HOME}/git")
        lines.append("")

    return lines


def _sdk_section(spec: ImageSpec) -> list[str]:
    """SDKs cloned at a release tag.

    The tag is written in literally rather than left as a moving branch, so
    rebuilding this file next month produces the same SDK.
    """
    lines: list[str] = []
    for extra in spec.sdk_extras:
        version = spec.version_for(extra)
        arg_name = f"{extra.key.replace('-', '_').upper()}_VERSION"
        lines += [
            f"# {extra.label}, pinned to the release tag resolved at generation",
            f"# time. Change {arg_name} to move it.",
            f"ARG {arg_name}={version}",
            *_run_steps(extra.command.format(version=f'"${arg_name}"')),
        ]
        for name, value in extra.env:
            lines.append(f"ENV {name}={value}")
        lines.append("")
    return lines


def _run_steps(command: str) -> list[str]:
    """Render a command as a RUN, one shell step per line.

    A multi-step build reads far better with each `&&` on its own line, and a
    single long step still gets wrapped at its flags.
    """
    steps = command.split(" && ")
    if len(steps) == 1:
        return _wrapped_run(command)
    lines = _wrapped_run(steps[0])
    for step in steps[1:]:
        lines[-1] += " \\"
        wrapped = _wrapped_run(step)
        # _wrapped_run prefixes "RUN "; this is a continuation, not a new one.
        wrapped[0] = " && " + wrapped[0][4:]
        lines.extend(wrapped)
    return lines


def _wrapped_run(command: str, width: int = 76) -> list[str]:
    """Split a long command across continuation lines at flag boundaries."""
    tokens = command.split(" ")
    lines: list[str] = []
    current = "RUN"
    for token in tokens:
        candidate = f"{current} {token}"
        # Break before a flag rather than mid-argument, so each line reads.
        if len(candidate) > width and token.startswith("--") and current != "RUN":
            lines.append(current + " \\")
            current = "        " + token
        else:
            current = candidate
    lines.append(current)
    return lines


def _verify_command(spec: ImageSpec) -> str:
    """Commands proving the toolchain works, joined into one RUN."""
    checks: list[str] = []
    if any(p.startswith(("gcc-arm", "arm-none-eabi-gcc")) for p in spec.packages):
        checks.append("arm-none-eabi-gcc --version")
    if spec.needs_rust:
        checks.append("rustc --version")
        checks.append("rustup target list --installed")
        for extra in spec.extras:
            if extra.key == "cargo-binutils":
                checks.append("cargo size --version")
            elif extra.key == "probe-rs-tools":
                checks.append("probe-rs --version")
    for extra in spec.sdk_extras:
        if extra.verify:
            checks.append(extra.verify)
    if lcov.can_check(spec.packages, spec.distro.key):
        # Last, because it changes directory.
        checks += lcov.check_steps()
    if not checks:
        checks.append("true")
    return " \\\n && ".join(checks)


def build_command(spec: ImageSpec, containerfile: str = "Containerfile") -> list[str]:
    """The podman argv that builds this image.

    Resolved rather than taken from PATH: an application started before podman
    was installed inherits a PATH without it.
    """
    from .podman import executable

    return [
        executable() or "podman",
        "build",
        "--tag",
        spec.reference,
        "--file",
        containerfile,
        ".",
    ]


def summarise(spec: ImageSpec) -> str:
    """One-line description of what will be built."""
    extras = spec.extras
    bits = [f"{len(spec.packages)} packages"]
    if extras:
        bits.append(f"{len(extras)} extras")
        bits.append(f"Rust {spec.rust_toolchain}")
    return f"{spec.distro.label}: " + ", ".join(bits)
